- rpm_key:
      state: present
      key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
- rpm_key:
      state: present
      key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8

- name: Install epel repo.
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
    state: present

- name: Install PHP Remi Repository
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-8.rpm update_cache=yes state=latest
 
- name: Enable PHP Remi Repository
  command: dnf module reset php -y
  command: dnf module enable php:remi-7.4 -y
 
- name: Install PHP Extensions
  yum: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"
